### ISSUE TITLE
[Req} Binaries of Milky Tracker for AmigaOS 3.1 (or higher) on 68k Amiga platforms

### ISSUE THREAD

**Issue by ajack2001my** [AmigaPorts/MilkyTracker#40]
I see work done on this but can't seem to find binaries to install. Can somebody compile or show me where I can get the MilkyTracker binaries to run on my 030 (WB 3.2) system? Thanks in advance.

**Comment by MBeijer** [comment]
Sorry, but milkytracker won’t be useful on a 030 system. It requires at least a 060
