### ISSUE TITLE
Website in the about section is down

### ISSUE THREAD

**Issue by caseyjoy** [AmigaPorts/MilkyTracker#41]
The website in the about section (www.eevul.net/milkytracker) appears to be down. 

It seems to be alternating between showing a default empty wordpress file:
```
<?php
/**
 * Front to the WordPress application. This file doesn't do anything, but loads
 * wp-blog-header.php which does and tells WordPress to load the theme.
 *
 * @package WordPress
 */

/**
 * Tells WordPress to load the WordPress theme and output it.
 *
 * @var bool
 */
define( 'WP_USE_THEMES', true );

/** Loads the WordPress Environment and Template */
require( dirname( __FILE__ ) . '/wp-blog-header.php' );

```

 and not connecting at all. I'm getting an "Unable to connect / An error occurred during a connection to www.eevul.net." message instead in those cases.

**Comment by MBeijer** [comment]
Thanks for letting me know!

**Comment by MBeijer** [comment]
@caseyjoy https://dl.amigadev.com/ for MilkyTracker downloads
